#!/bin/bash
# zinst package create manager   
# Made by Jiook Yang
# ralf.yang@gsshop.com
# Version 1.0.3

PWD=`pwd`
cd $PWD

if [[ `echo $1 | grep "\-"` != "" ]]
	then
		echo "==========================================="
		echo " You can use \"-\" mark on package name "
		echo " Please change a package name to the other "
		echo "==========================================="
		exit 0;
		
	fi




zicf_checker=`echo $1 | grep .zicf`

### check .zicf file
if [[ $zicf_checker = "" ]];
then
	echo "==========================================="
	echo "Please make sure type the zicf target file"
	echo "ex) zinst_creator start_tomcat.zicf"
	echo "or you can use debug mode by \"--debug\" "
	echo "==========================================="
else

	### Base infomation & zicf data parsing
	ZICF=$1
	ZinstDir="/data/zinst"
	ZinstSourceDir="/data/vault/Source"


	Packagename=`cat $ZICF |grep ^PACKAGENAME |awk '{print $3}'`
	ZinstPackageDir="$ZinstDir/$Packagename"

	Version=`cat $ZICF |grep ^VERSION |awk '{print $3}'`
	Authorized=`cat $ZICF |grep ^AUTHORIZED |awk '{print $3}'` 
	Owner=`cat $ZICF |grep ^OWNER |awk '{print $3}'`
	Group=`cat $ZICF |grep ^GROUP |awk '{print $3}'`
	Perm=`cat $ZICF |grep ^PERM |awk '{print $3}'`
	Custodian=`cat $ZICF |grep ^CUSTODIAN |awk '{print $3}'`
	Crontab=`cat $ZICF |grep ^CRON |awk '{print $1}'`


	Description=`cat $ZICF |grep ^DESCRIPTION |awk '{print $0}'`


	### Message output
	echo ""
	echo Making a package..... $PWD/$Packagename-$Version.zinst
	echo ""


	### File banding & compressing
	## zicf 
	tar cf $Packagename.tar $ZICF
	echo $ZICF > filechecker

	## Source File type
	tar rf $Packagename.tar `cat ./$ZICF |grep ^FILE | awk '{print $6}'`
	cat ./$ZICF |grep ^FILE | awk '{print $6}' >> filechecker

	## Conf File type
	tar rf $Packagename.tar `cat ./$ZICF |grep ^CONF | awk '{print $6}'`
	cat ./$ZICF |grep ^CONF | awk '{print $6}' >> filechecker

	## Compress and rename
	gzip  $Packagename.tar 
	mv $Packagename.tar.gz $Packagename-$Version.zinst 

	sed -i 's/\.\.\///g' filechecker 



	### File checker 
	File_checker=`cat ./filechecker`
	Tar_file=`tar tvf ./$Packagename-$Version.zinst | awk '{print $6}'`

	if [[ $ZICF != "$Packagename.zicf" ]];
	then
		echo "====================================================================="
		echo "  Package-name in the zicf is not same with zicf-file name."
		echo "  Please check this issue out and create new name for make sure that."
		echo "  or please remove directory name like this ./  "
		echo "====================================================================="
		rm -f ./$Packagename-$Version.zinst 
	fi

	if [[ $File_checker != $Tar_file ]];
	then
		echo "====================================================================="
		echo "Error has been occurred. Please check the file list in the zicf again"
		echo "====================================================================="
		rm -f ./$Packagename-$Version.zinst 
	fi


	if [[ $2 = "--debug" ]]
	then	
		echo "====================================================================="
		echo  zicf file checking...
		echo "====================================================================="
		echo "$File_checker"
		echo "====================================================================="
		echo ""
		echo ""
		echo "====================================================================="
		echo  Package file checking...
		echo "====================================================================="
		echo "$Tar_file"
	else
		rm -f ./filechecker
	fi
fi
